[versions]
isPreview = "false" # true

# https://developer.android.com/studio/releases/build-tools.html#notes
buildTools = "36.1.0"
buildToolsPreview = "37.0.0-rc1"

minSdk = "23"

compileSdk = "36"
compileSdkMinor = "1"
compileSdkPreview = "CinnamonBun"
# compileSdkPreview = "CANARY"

compileSdkExtension = "20" # 36.1-ext20

targetSdk = "36"
targetSdkPreview = "CinnamonBun"
# targetSdkPreview = "CANARY"

# https://github.com/android/ndk/releases
ndk = "29.0.14206865"
# https://cmake.org/cmake/help/latest/release/index.html
cmake = "4.1.2"

versionCode = "71"
versionName = "1.18.6_unpublished"

javaToolchain = "21"

[libraries]

[bundles]

[plugins]